In [ ]:

import numpy as np

In [2]:
temperature_w1=np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])

In [3]:
print(temperature_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [4]:
print("Shape:",temperature_w1.shape)

Shape: (7,)


In [5]:
print("Data Type:",temperature_w1.dtype)

Data Type: float64


In [6]:
print("Number of Elements:",temperature_w1.size)

Number of Elements: 7


In [7]:
temperature_f=(temperature_w1 * 9/5) + 32


In [8]:
print("Temperature in Fahrenheit:")
print(temperature_f)

Temperature in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [9]:
print("Maximum Temperature:",temperature_w1.max())

Maximum Temperature: 26.1


In [10]:
print("Minimum Temperature:",temperature_w1.min())

Minimum Temperature: 20.8


In [11]:
print("Mean Temperature:",temperature_w1.mean())

Mean Temperature: 23.542857142857144


In [12]:
print("First three days:")
print(temperature_w1[:3])

First three days:
[22.5 25.3 20.8]


In [13]:
print("Weekend Temperature:")
print(temperature_w1[-2:])

Weekend Temperature:
[24.8 21.9]


In [14]:
print("Middle three days:")
print(temperature_w1[2:5])

Middle three days:
[20.8 23.4 26.1]


In [15]:
temperatures=np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9],[19.2,22.5,21.3,24.0,23.5,22.8,20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [16]:
print("Shape:",temperatures.shape)

Shape: (2, 7)


In [17]:
print("Data Type:",temperatures.dtype)

Data Type: float64


In [18]:
print("Number of Elements:",temperatures.size)

Number of Elements: 14


In [19]:
print("Week 1:")
print(temperatures[0])

Week 1:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [20]:
print("Week 2:")
print(temperatures[1])

Week 2:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [22]:
print("Weekends:")
print(temperatures[:,-2:])

Weekends:
[[24.8 21.9]
 [22.8 20.1]]


### Pandas Series

In [23]:
import pandas as pd

In [28]:
marks=pd.Series([95,92,89,85,80],
index=['Rank 1','Rank 2','Rank 3','Rank 4','Rank 5'])


In [29]:
print(marks)

Rank 1    95
Rank 2    92
Rank 3    89
Rank 4    85
Rank 5    80
dtype: int64


In [30]:
print(marks.iloc[0])

95


In [31]:
print(marks.loc[['Rank 1','Rank 2','Rank 3']])

Rank 1    95
Rank 2    92
Rank 3    89
dtype: int64


In [32]:
print(marks.iloc[2])

89


In [33]:
print(marks[marks > 90])

Rank 1    95
Rank 2    92
dtype: int64


In [35]:
marks.loc['Rank 1'] = 100


In [36]:
print(marks)

Rank 1    100
Rank 2     92
Rank 3     89
Rank 4     85
Rank 5     80
dtype: int64


In [37]:
marks=marks.drop('Rank 5')

In [38]:
print(marks)

Rank 1    100
Rank 2     92
Rank 3     89
Rank 4     85
dtype: int64


In [39]:
cgpa = marks / 10
print(cgpa)

Rank 1    10.0
Rank 2     9.2
Rank 3     8.9
Rank 4     8.5
dtype: float64


### Pandas DataFrame

In [40]:
import pandas as pd

In [42]:
transactions=pd.DataFrame({'TransactionID':[101,102,103,104,105,106,107,108,109,110],
                           'ProductCategory':['Electronics','Clothing','Electronics','Furniture',
                                              'Clothing','Electronics','Furniture','Clothing','Furniture',
                                              'Electronics'],
                           'Region':['North','South','North','East','West','North','East','West','South','North'],
                           'Amount':[200,150,300,450,200,250,300,180,350,400]})
print(transactions)
            

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [43]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [44]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [45]:
print(transactions.shape)

(10, 4)


In [46]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')


In [47]:
print(transactions.dtypes)

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object


In [48]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str  
 2   Region           10 non-null     str  
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes


In [49]:
print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [50]:
print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [51]:
filtered_data=transactions[(transactions['Region']=='North') &
    (transactions['Amount']>200)]
print(filtered_data)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [52]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [53]:
print(transactions['Region'].unique())

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str


In [54]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [55]:
transactions.loc[transactions['TransactionID']==102, 'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [56]:
transactions['Discount']=transactions['Amount']*0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [57]:
transactions=transactions[transactions['TransactionID']!=109]
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [58]:
transactions=transactions.drop('Discount',axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
